# Generated by Django 4.0.5 on 2022-06-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Женская', 'Женская'), ('Детская', 'Детская'), ('Мужская', 'Мужская')], max_length=15)),
                ('group', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('size', models.CharField(max_length=10)),
                ('discount', models.IntegerField()),
                ('images', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
