# Generated by Django 4.0.5 on 2022-06-10 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0002_remove_clothes_images_alter_clothes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('Мужская', 'Мужская'), ('Детская', 'Детская'), ('Женская', 'Женская')], max_length=15, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='image',
            name='clothes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app_shop.clothes'),
        ),
    ]
