# Generated by Django 4.0.5 on 2022-06-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0003_alter_clothes_type_alter_image_clothes'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothes',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='В наличии'),
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('Мужская', 'Мужская'), ('Женская', 'Женская'), ('Детская', 'Детская')], max_length=15, verbose_name='Тип'),
        ),
    ]
