# Generated by Django 4.0.5 on 2022-06-30 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0004_clothes_is_available_alter_clothes_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=100, verbose_name='Почта')),
                ('post_index', models.CharField(max_length=10, verbose_name='Индекс')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Оплачен')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('Женская', 'Женская'), ('Мужская', 'Мужская'), ('Детская', 'Детская')], max_length=15, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='OrderCloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('discount', models.IntegerField(verbose_name='Скидка')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='app_shop.clothes', verbose_name='Одежда')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clothes', to='app_shop.order', verbose_name='Заказ')),
            ],
        ),
    ]
