# Generated by Django 4.0.5 on 2022-06-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_order_alter_clothes_type_ordercloth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clothes',
            options={'verbose_name': 'Одежда', 'verbose_name_plural': 'Одежда'},
        ),
        migrations.RemoveField(
            model_name='ordercloth',
            name='discount',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('Детская', 'Детская'), ('Мужская', 'Мужская'), ('Женская', 'Женская')], max_length=15, verbose_name='Тип'),
        ),
    ]
