# Generated by Django 4.0.5 on 2022-06-30 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0006_alter_clothes_options_remove_ordercloth_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='username',
        ),
        migrations.AlterField(
            model_name='clothes',
            name='type',
            field=models.CharField(choices=[('Женская', 'Женская'), ('Детская', 'Детская'), ('Мужская', 'Мужская')], max_length=15, verbose_name='Тип'),
        ),
    ]
